### ISSUE TITLE
How to translate messages to other languages?

### ISSUE THREAD

**Issue by erral** [RadarCOVID/radar-covid-backend-configuration-server#4]
According to the README the texts and locales of the application are loaded from this configuration server:

https://github.com/RadarCOVID/radar-covid-backend-configuration-server#endpoints

But there are no translations in there, just spanish messages:

https://github.com/RadarCOVID/radar-covid-backend-configuration-server/blob/master/responses/response-texts.json

How can we help on translating those messages to other languages?

There are already some PRs to translate the Android app to Basque and Galician, and if that effort should be brought here, we would like to know it:

https://github.com/RadarCOVID/radar-covid-android/pull/24
https://github.com/RadarCOVID/radar-covid-android/pull/30

@xurxodiz

**Comment by JuanjoSalvador** [comment]
Android by default support multi-language, and it should be placed on the client, not the server. But both, server and client, only seems to have Castilian strings, no English, no Galician, etc, as they say on the server's README.

In the case of the strings are provided by the server, this repo seems like an older version of the current app.

**Comment by enolp** [comment]
I'm translating Radar COVID into Asturian due to lack of interest and obligations from different administrations, which is shame. But the thing is, Radar COVID is translated to English but no English strings are found in its repo. So, if someone has better info, please correct me.

**Comment by iCesofT** [comment]
Apps get the texts from this service and this service, as said in README, gets the texts from a CMS (Contentful). The JSON are samples for castillian (es-ES).

**Comment by xurxodiz** [comment]
Does this mean that PRs in `radar-covid-android` such as [#30](https://github.com/RadarCOVID/radar-covid-android/pull/30) or  [#24](https://github.com/RadarCOVID/radar-covid-android/pull/24) are of no use, as the app disregards those files?

**Comment by erral** [comment]
Yes @xurxodiz it seems so. They manage the translation strings as content in a CMS externally to the apps. I already closed my PR.

**Comment by xurxodiz** [comment]
(Yeah I know, I gathered as much, but I wanted to pressure an official response and/or alternative solution 😉 )
