### ISSUE TITLE
Access to Contentful assets for translation if possible

### ISSUE THREAD

**Issue by enolp** [RadarCOVID/radar-covid-backend-configuration-server#5]
As it was said here: https://github.com/RadarCOVID/radar-covid-backend-configuration-server/issues/4, translations are place on a server which is not opensource (?) so, it would be possible to opensource the assets which Radar COVID uses to display strings to users? I mean, due to a lack of obligations and interest, Gobierno de España (including autonomous administrations) did not translate this app/assets/whatever-thing to other co-official languages [Galician, Basque, Catalan, Occitan (Aranese)] and/or non-official but protected languages by law [Asturian and Aragonese]. Given that and in order to fix this situation, I think the community should have access to those assets and translate them until official translators from different autonomous administrations take care of them if there's any.

Me and other members of the community are translating Radar COVID to Asturian, Basque and Galician, making this software accessible to more people who want to use this app in the language they want and doing the job our administrations must do to grant rights and respect the law.

Sorry for turning this Issue into something a bit political but when this app first launched, it was translated ONLY to Spanish and English, and I must to say it. Now let's focus into the software itself.

**Comment by iCesofT** [comment]
With the latest version, there will be more languages, as requirements. As long as the application is approved on the stores, we will enable those languages (Multi-language - co-official languages).

**Comment by enolp** [comment]
First of all, thanks for replying me but I must to express my disagreement here.

I don't want to be rude but, in which part of Spain is English a co-official language? "Multi-language" support cannot be equals to "co-official languages" because Asturian, Aragonese and English are lacking it BUT, in case of Asturian there are some laws which protect it like article 4 from Estatutu d'Autonomía p'Asturies (link in Spanish: https://www.boe.es/buscar/pdf/1982/BOE-A-1982-634-consolidado.pdf), and Llei d'Usu y Promoción del Asturianu (link in Spanish: https://www.boe.es/buscar/pdf/1998/BOE-A-1998-10126-consolidado.pdf).
Aragonese also has its own legislation from article 7 of Estauto d'Autonomía d'Aragón (link in Spanish: https://www.boe.es/buscar/act.php?id=BOE-A-2007-8444) and Lei d'Uso, Protección y Promoción d'As Luengas Propias d'Aragón (link in Spanish: https://www.boe.es/eli/es-ar/l/2013/05/09/3/dof/spa/pdf).

On the other hand, English has no law which protect it or make it co-official (which is unconstitutional) because it is not a traditional or vernacular language of Spain as it is said in article 3 from Constitución Española (link in Spanish: https://www.boe.es/buscar/pdf/1978/BOE-A-1978-31229-consolidado.pdf), and some judicial resolutions from Tribunal Constitucional has released and prove which I cannot find right now.

I need more clarification about your statement because we are all seeing that Gobierno de España is breaking their own laws, voted by deputies which are elected every ~4 years on elections by citizens.

Have a nice day.

P.D.: Your reply does not "fix" my issue

**Comment by pantic79** [comment]
@enolp, your complain is noted. Please, as you said, let's focus into the software and not in political issues.
