### ISSUE TITLE
[Question] Contentful space and token

### ISSUE THREAD

**Issue by AML14** [RadarCOVID/radar-covid-backend-configuration-server#6]
Hi,

First of all, congratulations for the project. It's nice to see it open source.

I'm trying to deploy it locally and play around with it, however, I don't get a few endpoints to work (e.g., `/masterData/ccaa`), and I think it's something related to Contentful: Whenever I make a request to such endpoint, I get a 500 status code, which logs the following error:

```
[DEBUG] 2020-09-24 13:28:54.371 Loggable - [3201ab301267a404] - Controller : Request Path info :/masterData/ccaa
[DEBUG] 2020-09-24 13:28:54.371 Loggable - [3201ab301267a404] - Controller : End Header Section of request 
[DEBUG] 2020-09-24 13:28:54.457 Loggable - [3201ab301267a404] -    ************************* INIT SERVICE ******************************
[DEBUG] 2020-09-24 13:28:54.461 Loggable - [3201ab301267a404] -    Service : Entering in Method :  es.gob.radarcovid.configuration.business.impl.MasterDataServiceImpl
[DEBUG] 2020-09-24 13:28:54.462 Loggable - [3201ab301267a404] -    Service : Method :  getAutonomousCommunities
[DEBUG] 2020-09-24 13:28:54.462 Loggable - [3201ab301267a404] -    Service : Arguments :  [es-ES, false]
[DEBUG] 2020-09-24 13:28:54.463 Loggable - [3201ab301267a404] -    Service : Target class : es.gob.radarcovid.configuration.business.impl.MasterDataServiceImpl
[ERROR] 2020-09-24 13:28:55.957 Loggable - [3201ab301267a404] -    Service :  An exception has been thrown in getAutonomousCommunities ()
[ERROR] 2020-09-24 13:28:55.959 Loggable - [3201ab301267a404] -    Service :  Cause : null
[DEBUG] 2020-09-24 13:28:55.959 Loggable - [3201ab301267a404] -    ************************** END SERVICE ******************************
[DEBUG] 2020-09-24 13:28:55.964 Loggable - [3201ab301267a404] - ************************* END CONTROLLER **********************************
[DEBUG] 2020-09-24 13:28:55.969 Loggable - [3201ab301267a404] - Controller : Controller es.gob.radarcovid.configuration.controller.MasterDataController.getCcaa () execution time : 1633 ms
[DEBUG] 2020-09-24 13:28:55.972 Loggable - [3201ab301267a404] - Controller : Controller Return value :  <500 INTERNAL_SERVER_ERROR, null>
```

By taking a look at the code and debugging it, I found that what is failing is the request to Contentful in `es.gob.radarcovid.configuration.contentful.client.impl.ContentfulClientImpl#getAutonomousCommunities(String locale)`, since no Contentful access token is provided. Actually the space isn't provided either, as shown in the application.yml:

```yaml
contentful:
  url: ${SERVICES.CONTENTFUL.URL:https://preview.contentful.com/}
  space: ${SERVICES.CONTENTFUL.SPACE:}
  token: ${SERVICES.CONTENTFUL.TOKEN:}
  environment: ${SERVICES.CONTENTFUL.ENVIRONMENT:master}
```

I don't know anything about Contentful, but is there any way to make the configuration-server-service do the right calls to Contentful so that it returns the correct data when requesting `/masterData/ccaa` or `/texts`, for instance?

Thanks in advance!

Alberto.

**Comment by pantic79** [comment]
Hello,

perhaps you could check for the contentful community version. Currently it works just for two locales. We should evaluate to publish an export of content and content types for every release in order you can import this data.

Thanks.

**Comment by AML14** [comment]
Hi,

Thanks for answering. Sorry, I'm not familiar with Contentful at all. Should I create an account so that I can use that access token for the `SERVICES.CONTENTFUL.TOKEN` variable?

Besides that, what's up with the variables `SPACE` and `ENVIRONMENT`? Should I leave `SPACE` blank and `ENVIRONMENT` set to `master` or should I change those too?

Thanks.

**Comment by pantic79** [comment]
That's right. Space and Environment are Contentful concepts. Please, check [this](https://www.contentful.com/help/contentful-101/).

Thanks.

**Comment by iCesofT** [comment]
Hi.. if you don't mind @AML14 & @pantic79, I close the issue since it's not an issue per-se.
